/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_api_images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic Search */
        post: operations["semantic_search_api_images_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_api_images_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deleted Images */
        get: operations["list_deleted_images_api_images_trash_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Image */
        post: operations["restore_image_api_images__image_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Purge Image */
        delete: operations["purge_image_api_images__image_id__purge_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Thumbnail */
        get: operations["get_image_thumbnail_api_images__image_id__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Content */
        get: operations["get_image_content_api_images__image_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Image */
        get: operations["download_image_api_images__image_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Detail */
        get: operations["get_image_detail_api_images__image_id__get"];
        put?: never;
        post?: never;
        /** Delete Image */
        delete: operations["delete_image_api_images__image_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Image Title */
        patch: operations["update_image_title_api_images__image_id__title_patch"];
        trace?: never;
    };
    "/api/images/{image_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Image Tags */
        patch: operations["update_image_tags_api_images__image_id__tags_patch"];
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /** Update Tag */
        patch: operations["update_tag_api_tags__tag_id__patch"];
        trace?: never;
    };
    "/api/ai/provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Status */
        get: operations["provider_status_api_ai_provider_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/search-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Understand Search */
        post: operations["understand_search_api_ai_search_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/selling-points/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match Selling Points */
        post: operations["match_selling_points_api_ai_selling_points_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/images/{image_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Image */
        post: operations["analyze_image_api_ai_images__image_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Logs */
        get: operations["list_audit_logs_api_admin_users_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/admin/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_admin_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditLogRead */
        AuditLogRead: {
            /** Id */
            id: string;
            /** Actoruserid */
            actorUserId?: string | null;
            /** Action */
            action: string;
            /** Targettype */
            targetType: string;
            /** Targetid */
            targetId?: string | null;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Requestid */
            requestId?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** Body_upload_image_api_images_upload_post */
        Body_upload_image_api_images_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Title */
            title?: string | null;
            /**
             * Tag Ids
             * @default
             */
            tag_ids: string;
            /**
             * Primary Tag Id
             * @default
             */
            primary_tag_id: string;
            /**
             * Categories
             * @default
             */
            categories: string;
        };
        /** ConfidenceTag */
        ConfidenceTag: {
            /** Tag */
            tag: string;
            /** Confidence */
            confidence: number;
            /** Dimension */
            dimension?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** AnalysisRunRead */
        AnalysisRunRead: {
            /** Id */
            id: string;
            /** Task */
            task: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Taxonomyversion */
            taxonomyVersion?: string | null;
            /** Modelprovider */
            modelProvider?: string | null;
            /** Modelname */
            modelName?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ContentTagRead */
        ContentTagRead: {
            /** Id */
            id: string;
            /** Tagname */
            tagName: string;
            /** Confidence */
            confidence: number;
            /** Dimension */
            dimension?: string | null;
        };
        /** ImageSemanticProfile */
        ImageSemanticProfile: {
            /** Visualfacts */
            visualFacts?: string[];
            /** Businessintent */
            businessIntent?: string;
            /** Searchphrases */
            searchPhrases?: string[];
            /** Exclusionboundaries */
            exclusionBoundaries?: string[];
        };
        /** SemanticProfileRead */
        SemanticProfileRead: {
            /** Visualfacts */
            visualFacts?: string[];
            /** Businessintent */
            businessIntent?: string;
            /** Searchphrases */
            searchPhrases?: string[];
            /** Exclusionboundaries */
            exclusionBoundaries?: string[];
        };
        /** ExpandedSearchTag */
        ExpandedSearchTag: {
            /** Tag */
            tag: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "exact" | "strong" | "medium" | "weak";
            /** Reason */
            reason: string;
            /** Weight */
            weight: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageAnalysisResult */
        ImageAnalysisResult: {
            /**
             * Imagetype
             * @enum {string}
             */
            imageType: "function" | "scene_emotion" | "scene_functional";
            /** Imagesummary */
            imageSummary: string;
            /** Semanticprofile */
            semanticProfile?: components["schemas"]["ImageSemanticProfile"];
            /** Contenttags */
            contentTags?: components["schemas"]["ConfidenceTag"][];
            /** Secondarylabels */
            secondaryLabels?: components["schemas"]["SecondaryLabel"][];
            /** Recommendedsearchwords */
            recommendedSearchWords?: string[];
            /** Negativetags */
            negativeTags?: string[];
        };
        /** BusinessLabelRead */
        BusinessLabelRead: {
            /** Id */
            id: string;
            /** Labelcode */
            labelCode: string;
            /** Tagid */
            tagId: string;
            /** Tagname */
            tagName: string;
            /** Systemname */
            systemName?: string | null;
            /** Origin */
            origin: string;
            /** Role */
            role: string;
            /** Reviewstatus */
            reviewStatus: string;
            /** Confidence */
            confidence?: number | null;
            /** Evidencelevel */
            evidenceLevel?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** BusinessLabelReviewUpdate */
        BusinessLabelReviewUpdate: {
            /** Reviewstatus */
            reviewStatus: "accepted" | "pending" | "rejected";
        };
        /** SearchFeedbackCreate */
        SearchFeedbackCreate: {
            /** Searchlogid */
            searchLogId?: string | null;
            /** Keyword */
            keyword: string;
            /** Feedbacktype */
            feedbackType: "not_relevant" | "too_few_results" | "need_different_style" | "asset_request";
            /** Note */
            note?: string | null;
        };
        /** SearchFeedbackRead */
        SearchFeedbackRead: {
            /** Id */
            id: string;
            /** Searchlogid */
            searchLogId?: string | null;
            /** Keyword */
            keyword: string;
            /** Feedbacktype */
            feedbackType: string;
            /** Note */
            note?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ImageDetailRead */
        ImageDetailRead: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Filename */
            fileName: string;
            /** Contenturl */
            contentUrl: string;
            /** Thumbnailurl */
            thumbnailUrl: string;
            /** Downloadurl */
            downloadUrl: string;
            /** Mediatype */
            mediaType: string;
            /** Sizebytes */
            sizeBytes: number;
            /** Uploader */
            uploader: string;
            /** Downloadcount */
            downloadCount: number;
            /** Categories */
            categories: string[];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Deletedat */
            deletedAt?: string | null;
            /** Tags */
            tags: components["schemas"]["TagRead"][];
            /** Imagesummary */
            imageSummary?: string | null;
            /** Semanticprofile */
            semanticProfile?: components["schemas"]["SemanticProfileRead"] | null;
            /** Relatedimages */
            relatedImages?: components["schemas"]["ImageRead"][];
            /** Contenttags */
            contentTags?: components["schemas"]["ContentTagRead"][];
            /** Level2Categories */
            level2Categories?: components["schemas"]["Level2CategoryRead"][];
            /** Businesslabels */
            businessLabels?: components["schemas"]["BusinessLabelRead"][];
            /** Analysisruns */
            analysisRuns?: components["schemas"]["AnalysisRunRead"][];
        };
        /** ImageListResponse */
        ImageListResponse: {
            /** Items */
            items: components["schemas"]["ImageRead"][];
            /** Nextcursor */
            nextCursor?: string | null;
            /** Hasmore */
            hasMore: boolean;
        };
        /** ImageRead */
        ImageRead: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Filename */
            fileName: string;
            /** Contenturl */
            contentUrl: string;
            /** Thumbnailurl */
            thumbnailUrl: string;
            /** Downloadurl */
            downloadUrl: string;
            /** Mediatype */
            mediaType: string;
            /** Sizebytes */
            sizeBytes: number;
            /** Uploader */
            uploader: string;
            /** Downloadcount */
            downloadCount: number;
            /** Categories */
            categories: string[];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Deletedat */
            deletedAt?: string | null;
            /** Tags */
            tags: components["schemas"]["TagRead"][];
        };
        /** ImageTagsUpdate */
        ImageTagsUpdate: {
            /** Tagids */
            tagIds: string[];
            /** Primarytagid */
            primaryTagId?: string | null;
        };
        /** ImageTitleUpdate */
        ImageTitleUpdate: {
            /** Title */
            title: string;
        };
        /** Level2CategoryRead */
        Level2CategoryRead: {
            /** Id */
            id: string;
            /** Categoryname */
            categoryName: string;
            /** Confidence */
            confidence: number;
            /** Reason */
            reason?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserRead"];
            /** Csrftoken */
            csrfToken: string;
        };
        /** PasswordReset */
        PasswordReset: {
            /** Password */
            password: string;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Provider */
            provider: string;
            /** Configured */
            configured: boolean;
            /**
             * Modelname
             * @default
             */
            modelName: string;
        };
        /** ScoredImage */
        ScoredImage: {
            image: components["schemas"]["ImageRead"];
            /**
             * Matchlevel
             * @enum {string}
             */
            matchLevel: "S" | "A" | "B" | "C";
            /** Finalscore */
            finalScore: number;
            /** Matchreasons */
            matchReasons: string[];
            /** Matchedlevel1Tags */
            matchedLevel1Tags: string[];
            /** Matchedlevel2Categories */
            matchedLevel2Categories: string[];
        };
        /** SearchCategoryMatch */
        SearchCategoryMatch: {
            /** Category */
            category: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "direct" | "related" | "fallback";
            /** Reason */
            reason: string;
            /** Weight */
            weight: number;
        };
        /** SearchIntentRequest */
        SearchIntentRequest: {
            /** Keyword */
            keyword: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Keyword */
            keyword: string;
            /**
             * Limit
             * @default 12
             */
            limit: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["ScoredImage"][];
            /**
             * Hasmore
             * @default false
             */
            hasMore: boolean;
            /**
             * Searchmode
             * @default fuzzy
             */
            searchMode: "fuzzy" | "meilisearch";
            /**
             * Fallback
             * @default false
             */
            fallback: boolean;
            /** Fallbackreason */
            fallbackReason?: string | null;
            /** Searchlogid */
            searchLogId?: string | null;
            /** Matchsummary */
            matchSummary: string;
        };
        /** SearchUnderstanding */
        SearchUnderstanding: {
            /** Originalquery */
            originalQuery: string;
            /** Normalizedquery */
            normalizedQuery: string;
            /** Searchintent */
            searchIntent: string;
            /** Querytype */
            queryType: string;
            /** Expandedlevel1Tags */
            expandedLevel1Tags?: components["schemas"]["ExpandedSearchTag"][];
            /** Matchedlevel2Categories */
            matchedLevel2Categories?: components["schemas"]["SearchCategoryMatch"][];
            /** Excludetags */
            excludeTags?: string[];
            /**
             * Searchstrategy
             * @default
             */
            searchStrategy: string;
        };
        /** SecondaryLabel */
        SecondaryLabel: {
            /** System */
            system: string;
            /** Label */
            label: string;
            /** Confidence */
            confidence: number;
            /**
             * Evidencelevel
             * @enum {string}
             */
            evidenceLevel: "A" | "B" | "C";
            /**
             * Role
             * @enum {string}
             */
            role: "primary" | "secondary";
            /** Reason */
            reason: string;
        };
        /** SellingPoint */
        SellingPoint: {
            /** Pointkey */
            pointKey: string;
            /** Pointname */
            pointName: string;
            /** Weight */
            weight: number;
        };
        /** SellingPointMatchResult */
        SellingPointMatchResult: {
            /** Matched */
            matched?: components["schemas"]["SellingPointSystemMatch"][];
            /** Expandkeywords */
            expandKeywords?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
        };
        /** SellingPointRequest */
        SellingPointRequest: {
            /** Copy */
            copy: string;
        };
        /** SellingPointSystemMatch */
        SellingPointSystemMatch: {
            /** Systemkey */
            systemKey: string;
            /** Systemname */
            systemName: string;
            /** Points */
            points: components["schemas"]["SellingPoint"][];
        };
        /** TagCreate */
        TagCreate: {
            /** Name */
            name: string;
            /**
             * Color
             * @default #6B7280
             */
            color: string;
            /** Parentid */
            parentId?: string | null;
            /**
             * Issecondary
             * @default false
             */
            isSecondary: boolean;
            /**
             * Assignable
             * @default true
             */
            assignable: boolean;
        };
        /** TagRead */
        TagRead: {
            /** Id */
            id: string;
            /** Code */
            code?: string | null;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Parentid */
            parentId?: string | null;
            /** Parentname */
            parentName?: string | null;
            /**
             * Issecondary
             * @default false
             */
            isSecondary: boolean;
            /**
             * Nodetype
             * @default custom
             */
            nodeType: string;
            /**
             * Assignable
             * @default true
             */
            assignable: boolean;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Taxonomyversion */
            taxonomyVersion?: string | null;
            /**
             * Sortorder
             * @default 0
             */
            sortOrder: number;
            /**
             * Imagecount
             * @default 0
             */
            imageCount: number;
        };
        /** TagUpdate */
        TagUpdate: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
            /** Parentid */
            parentId?: string | null;
            /** Issecondary */
            isSecondary?: boolean | null;
            /** Assignable */
            assignable?: boolean | null;
            /** Status */
            status?: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "business" | "designer" | "admin";
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Role
             * @enum {string}
             */
            role: "business" | "designer" | "admin";
            /** Isactive */
            isActive: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Role */
            role?: ("business" | "designer" | "admin") | null;
            /** Isactive */
            isActive?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                piancton_session?: string | null;
                piancton_csrf?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_images_api_images_get: {
        parameters: {
            query?: {
                keyword?: string | null;
                tagIds?: string | null;
                cursor?: string | null;
                limit?: number;
                sortBy?: string;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    semantic_search_api_images_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_images_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_images_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deleted_images_api_images_trash_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_image_api_images__image_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_image_api_images__image_id__purge_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_thumbnail_api_images__image_id__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_content_api_images__image_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_image_api_images__image_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_detail_api_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_api_images__image_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_image_title_api_images__image_id__title_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageTitleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_image_tags_api_images__image_id__tags_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageTagsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_business_label_api_images__image_id__business_labels__label_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                image_id: string;
                label_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessLabelReviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_api_tags_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tag_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_api_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                tag_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_status_api_ai_provider_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    understand_search_api_ai_search_intent_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchUnderstanding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_selling_points_api_ai_selling_points_match_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SellingPointRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellingPointMatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_image_api_ai_images__image_id__analyze_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                image_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageAnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_logs_api_admin_users_audit_logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                piancton_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_admin_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: {
                piancton_csrf?: string | null;
                piancton_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
